# Generated by Django 4.0.2 on 2022-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_poll_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(related_name='choice_answer', to='questionnaire.Choice', verbose_name='Вариант'),
        ),
    ]
